### create post
POST http://localhost:8080/posts
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIzTTRPKzhMZTlwNHpncUlhbUhQekZnPT0iLCJqdGkiOiJjYTlYUzFwT1RRcHNubFJaYzNncHhnPT0iLCJpYXQiOjE2OTAzNzU2NjUsImV4cCI6MTY5MDQ2MjA2NX0.6Eghoho8nIb4msK_zVSc_9TprrB91NGJ0BsF-BZ1x2o

{
  "title": "제목",
  "description": "내용",
  "image": "",
  "category": "CLIMBING",
  "accessLevel": false,
  "hashtag": [
    {"keyword": "오운완"},
    {"keyword": "운동"}
  ]
}

### update post
PUT http://localhost:8080/posts/9
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIzTTRPKzhMZTlwNHpncUlhbUhQekZnPT0iLCJqdGkiOiJjYTlYUzFwT1RRcHNubFJaYzNncHhnPT0iLCJpYXQiOjE2OTAzNzU2NjUsImV4cCI6MTY5MDQ2MjA2NX0.6Eghoho8nIb4msK_zVSc_9TprrB91NGJ0BsF-BZ1x2o

{
  "title": "제목2",
  "description": "내용2",
  "image": "",
  "category": "RUNNING",
  "accessLevel": true,
  "hashtag": [
    {"keyword": "러닝" },
    {"keyword": "등산" }
  ]
}

### delete post
DELETE http://localhost:8080/posts/9
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIzTTRPKzhMZTlwNHpncUlhbUhQekZnPT0iLCJqdGkiOiJjYTlYUzFwT1RRcHNubFJaYzNncHhnPT0iLCJpYXQiOjE2OTAzNzU2NjUsImV4cCI6MTY5MDQ2MjA2NX0.6Eghoho8nIb4msK_zVSc_9TprrB91NGJ0BsF-BZ1x2o

### create reply
POST http://localhost:8080/posts/10/comment
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIzTTRPKzhMZTlwNHpncUlhbUhQekZnPT0iLCJqdGkiOiJjYTlYUzFwT1RRcHNubFJaYzNncHhnPT0iLCJpYXQiOjE2OTAzNzU2NjUsImV4cCI6MTY5MDQ2MjA2NX0.6Eghoho8nIb4msK_zVSc_9TprrB91NGJ0BsF-BZ1x2o

{
  "comment": "반갑습니다."
}

### click post
GET http://localhost:8080/posts/11
Content-Type: application/json

