### 회원가입
POST http://localhost:8080/users/signup
Content-Type: application/json

{
  "email": "email@example.com",
  "gender": true,
  "nickname": "nickname",
  "password": "12345",
  "public_info": true
}

### 일반 로그인
POST http://localhost:8080/users/signin
Content-Type: application/json

{
  "nickname": "nickname",
  "password": "12345"
}