### 회원가입
POST http://localhost:8080/users/signup
Content-Type: application/json

{
  "email": "email@example.com",
  "gender": true,
  "nickname": "nickname",
  "password": "12345",
  "public_info": true
}

### 일반 로그인
POST http://localhost:8080/users/signin
Content-Type: application/json

{
  "nickname": "nickname",
  "password": "12345"
}

### 나의 정보 가져오기
GET http://localhost:8080/users/my
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ2SXV4aEEvUDVLWnNPbG5rQXNtYUFnPT0iLCJqdGkiOiJjYTlYUzFwT1RRcHNubFJaYzNncHhnPT0iLCJpYXQiOjE2OTA0MjUyNDMsImV4cCI6MTY5MDUxMTY0M30.wiMv5ezuEHzI56CBijasljrdAJXvL4vfHbsMNyhDNEM

### 회원정보 수정
PUT http://localhost:8080/users/my
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1ZStWZUN0OWFnVmUyS0xzN0w0S0xBPT0iLCJqdGkiOiJBc0thbHVPUzcwV0FHYnpVeFl5U01nPT0iLCJpYXQiOjE2OTA0MzU1MTAsImV4cCI6MTY5MDUyMTkxMH0.Zlh8Jg9Ozi36hzH1npWuJHJo3AmbUd9cz5G_A0olq3I

{
  "exerciseChoice": [
    "HIKING", "WEIGHT"
  ],
  "gender": false,
  "introduction": "운동 같이 해요~",
  "password": "12345",
  "profilePicture": null,
  "publicInfo": true
}